version: "3"

vars:
  IMAGE_VERSION: "v0.0.1"
  IMAGE_NAME: "robotf/robotf-llm-tools"

tasks:
  default:
    desc: "Display available tasks"
    cmds:
      - task --list

  actionlint:
    desc: "Run actionlint"
    cmds:
      - echo "Running actionlint"
      - actionlint -config-file ./.github/actionlint.yml

  markdownlint:
    desc: "Run markdownlint"
    cmds:
      - echo "Running markdownlint"
      - markdownlint-cli2 "**/*.md"

  shellcheck:
    desc: "Run shellcheck"
    cmds:
      - echo "Running shellcheck"
      - shellcheck scripts/setup.sh

  yamllint:
    desc: "Run yamllint"
    cmds:
      - echo "Running yamllint"
      - yamllint -c .linters/yaml-linter.yml .

  pylint:
    desc: "Run pylint"
    cmds:
      - echo "Running pylint"
      - pylint **/*.py

  buildx:
    desc: Setup buildx
    cmds:
      - docker buildx create --name devops --use --bootstrap

  docker-build:
    desc: Build Docker Container
    # deps:
    #   - task: buildx
    cmds:
      - DOCKER_BUILDKIT=1 docker buildx build -f ./Dockerfile  --platform linux/amd64 --platform linux/arm64 -t {{.IMAGE_NAME}}:{{.IMAGE_VERSION}} .

  docker-load:
    desc: Build Docker Container
    # deps:
    #   - task: buildx
    cmds:
      - DOCKER_BUILDKIT=1 docker buildx build -f ./Dockerfile --load -t {{.IMAGE_NAME}}:{{.IMAGE_VERSION}} .

  docker-push:
    desc: Build and Push Docker Container with version and latest tags
    # deps:
    #   - task: buildx
    cmds:
      - echo "Building and pushing Docker images with version {{.IMAGE_VERSION}} and latest tags"
      - DOCKER_BUILDKIT=1 docker buildx build --push -f ./Dockerfile --platform linux/amd64 --platform linux/arm64 -t {{.IMAGE_NAME}}:{{.IMAGE_VERSION}} -t {{.IMAGE_NAME}}:latest .

  docker-run:
    desc: Run Docker Container
    cmds:
      - docker run -p 8969:8969 {{.IMAGE_NAME}}:{{.IMAGE_VERSION}} -v /var/run/docker.sock:/var/run/docker.sock

  docker-run-it:
    desc: Run Docker Container
    cmds:
      - docker run -it -p 8969:8969 {{.IMAGE_NAME}}:{{.IMAGE_VERSION}} /bin/sh

  run:
    desc: Run the Streamlit app
    cmds:
      - streamlit run RoboTF_LLM_Tools.py --server.port 8969

  version:
    desc: Return the version
    cmds:
      - echo {{.IMAGE_VERSION}}
